version: '3.8'

services:
  api:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --reload

  redis:
    image: redis:latest
    ports:
      - "6379:6379"